name = "bits"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

# wrangler.toml
name = "my-worker"
account_id = "your-account-id"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"  # 可选，自定义构建命令
format = "esm"            # 强制使用 ES 模块
esbuild = {
  target = "es2021",      # 指定目标语法版本
  format = "esm",         # 模块系统（esm 对应 ES2022+ 模块规范）
  supported = {
    "arrow-function": true,  # 按需启用特定语法支持
    "async-await": true
  }
}

kv_namespaces = [
  { binding = "bits", id = "65039a1ed58348e69d4b26de09b0e669" }
]
