name = "bits"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[build]
format = "esm"

[build.esbuild]
target = "es2021"
format = "esm"

[build.esbuild.supported]
arrow-function = true
async-await = true

kv_namespaces = [
  { binding = "bits", id = "65039a1ed58348e69d4b26de09b0e669" }
]
